SUMMARY = "OpenEthereum"
DESCRIPTION = "Built for mission-critical use: Miners, service providers, and exchanges need fast synchronisation and maximum uptime. OpenEthereum provides the core infrastructure essential for speedy and reliable services."
HOMEPAGE = "https://openethereum.github.io/"
LICENSE = "GPL-3.0"

LIC_FILES_CHKSUM = "file://LICENSE;md5=7702f203b58979ebbc31bfaeb44f219c"

inherit cargo
